name: app_cd

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - '**'
      - '.github/workflows/app_CD.yml'

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10.13.1'
  DEBUG_MESSAGE: 'CD実行!!'
concurrency:
  group: 'front-CD-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: install Vercel CLI
        run: pnpm add -g vercel@latest --allow-build=esbuild

      - name: Pull Vercel environment variables
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Set Vercel Enviroment Variables
        run: |
          vercel env rm DEBUG_MESSAGE production --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          echo "${{ env.DEBUG_MESSAGE }}" | vercel env add DEBUG_MESSAGE production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Verify Vercel Enviroment Variables
        run: |
          echo "Environment Variables:"
          vercel env ls --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Build Project
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          pwd; ls -la .vercel || true; ls -la .vercel/output || true
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DEBUG_MESSAGE: ${{ env.DEBUG_MESSAGE }}
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
