name: Front/CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "my-app/**"
      - ".github/workflows/my-app_CI.yml"
  push:
    branches: ["main"]
    paths:
      - "my-app/**"
      - ".github/workflows/my-app_CI.yml"
defaults:
  run:
    working-directory: my-app

env:
  NODE_VERSION: "22"
  PNPM_VERSION: "10.13.1"
  DEBUG_MESSAGE: "CI実行!!"

jobs:
  Launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: my-app/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

  lint:
    needs: Launch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: my-app/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
      - run: pnpm lint
        env:
          DEBUG_MESSAGE: ${{ env.DEBUG_MESSAGE }}
  format:
    needs: Launch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: my-app/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Prettier check (with diff)
        run: |
          pnpm prettier . --check || (
            echo '--- Prettier diff ---'
            pnpm format
            git diff
            exit 1
          )
  typecheck:
    needs: Launch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: my-app/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm tsc --noEmit
